// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7HOS_hnjNsOblBvXTWQfdpJbTXTHdEy4',
    appId: '1:1011375431235:web:4f87f65884615312e2fef6',
    messagingSenderId: '1011375431235',
    projectId: 'ushuttle-backend',
    authDomain: 'ushuttle-backend.firebaseapp.com',
    storageBucket: 'ushuttle-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjlBt9qfM2vlQt9wRytDOSg67eSjOWfQ',
    appId: '1:1011375431235:android:f17bb42f3ac0433be2fef6',
    messagingSenderId: '1011375431235',
    projectId: 'ushuttle-backend',
    storageBucket: 'ushuttle-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVTM0Tm6Gf-ZpyshljPs4QVzcMUk7DeM',
    appId: '1:1011375431235:ios:1f8b2445c77fcd35e2fef6',
    messagingSenderId: '1011375431235',
    projectId: 'ushuttle-backend',
    storageBucket: 'ushuttle-backend.appspot.com',
    iosClientId: '1011375431235-4jh2k9nrp063k9j9ujs8oknv36ee08gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ushuttlev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVTM0Tm6Gf-ZpyshljPs4QVzcMUk7DeM',
    appId: '1:1011375431235:ios:1f8b2445c77fcd35e2fef6',
    messagingSenderId: '1011375431235',
    projectId: 'ushuttle-backend',
    storageBucket: 'ushuttle-backend.appspot.com',
    iosClientId: '1011375431235-4jh2k9nrp063k9j9ujs8oknv36ee08gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ushuttlev1',
  );
}
