name: ushuttlev1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  open_route_service: ^1.2.2
  geolocator: ^8.0.5
  firebase_core: ^2.2.0
  expandable: ^5.0.1
  http: ^0.13.5
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.3.0
  loading_animation_widget:
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.16
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: "assets/images/splashhd.png"
  image_dark: "assets/images/splashhd.png"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/images/splashhd.png"
    icon_background_color: "#121212"
    image_dark: "assets/images/splashhd.png"
    icon_background_color_dark: "#121212"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/map/dhaka/13/6151/
    - assets/map/dhaka/13/6152/
    - assets/map/dhaka/13/6153/
    - assets/map/dhaka/13/6154/
    - assets/map/dhaka/14/12303/
    - assets/map/dhaka/14/12304/
    - assets/map/dhaka/14/12305/
    - assets/map/dhaka/14/12306/
    - assets/map/dhaka/14/12307/
    - assets/map/dhaka/14/12308/
    - assets/map/dhaka/15/24607/
    - assets/map/dhaka/15/24608/
    - assets/map/dhaka/15/24609/
    - assets/map/dhaka/15/24610/
    - assets/map/dhaka/15/24611/
    - assets/map/dhaka/15/24612/
    - assets/map/dhaka/15/24613/
    - assets/map/dhaka/15/24614/
    - assets/map/dhaka/15/24615/
    - assets/map/dhaka/15/24616/
    - assets/map/dhaka/15/24617/
    - assets/map/dhaka/16/49215/
    - assets/map/dhaka/16/49216/
    - assets/map/dhaka/16/49217/
    - assets/map/dhaka/16/49218/
    - assets/map/dhaka/16/49219/
    - assets/map/dhaka/16/49220/
    - assets/map/dhaka/16/49221/
    - assets/map/dhaka/16/49222/
    - assets/map/dhaka/16/49223/
    - assets/map/dhaka/16/49224/
    - assets/map/dhaka/16/49225/
    - assets/map/dhaka/16/49226/
    - assets/map/dhaka/16/49227/
    - assets/map/dhaka/16/49228/
    - assets/map/dhaka/16/49229/
    - assets/map/dhaka/16/49230/
    - assets/map/dhaka/16/49231/
    - assets/map/dhaka/16/49232/
    - assets/map/dhaka/16/49233/
    - assets/map/dhaka/16/49234/
    - assets/map/dhaka/17/98430/
    - assets/map/dhaka/17/98431/
    - assets/map/dhaka/17/98432/
    - assets/map/dhaka/17/98433/
    - assets/map/dhaka/17/98434/
    - assets/map/dhaka/17/98435/
    - assets/map/dhaka/17/98436/
    - assets/map/dhaka/17/98437/
    - assets/map/dhaka/17/98438/
    - assets/map/dhaka/17/98439/
    - assets/map/dhaka/17/98440/
    - assets/map/dhaka/17/98441/
    - assets/map/dhaka/17/98442/
    - assets/map/dhaka/17/98443/
    - assets/map/dhaka/17/98444/
    - assets/map/dhaka/17/98445/
    - assets/map/dhaka/17/98446/
    - assets/map/dhaka/17/98447/
    - assets/map/dhaka/17/98448/
    - assets/map/dhaka/17/98449/
    - assets/map/dhaka/17/98450/
    - assets/map/dhaka/17/98451/
    - assets/map/dhaka/17/98452/
    - assets/map/dhaka/17/98453/
    - assets/map/dhaka/17/98454/
    - assets/map/dhaka/17/98455/
    - assets/map/dhaka/17/98456/
    - assets/map/dhaka/17/98457/
    - assets/map/dhaka/17/98458/
    - assets/map/dhaka/17/98459/
    - assets/map/dhaka/17/98460/
    - assets/map/dhaka/17/98461/
    - assets/map/dhaka/17/98462/
    - assets/map/dhaka/17/98463/
    - assets/map/dhaka/17/98464/
    - assets/map/dhaka/17/98465/
    - assets/map/dhaka/17/98466/
    - assets/map/dhaka/17/98467/
    - assets/map/dhaka/17/98468/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
