// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPnCeiMGi8vvynJOWF2zfhLmJNlrRzcI',
    appId: '1:415414697651:web:47ed4672859523bccbbac6',
    messagingSenderId: '415414697651',
    projectId: 'ushuttle-backend-v2',
    authDomain: 'ushuttle-backend-v2.firebaseapp.com',
    storageBucket: 'ushuttle-backend-v2.appspot.com',
    measurementId: 'G-J4GRZV6FX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23QbHuidydnvSLEHMPAHlzXoGr414F3k',
    appId: '1:415414697651:android:231b2a92601f14f9cbbac6',
    messagingSenderId: '415414697651',
    projectId: 'ushuttle-backend-v2',
    storageBucket: 'ushuttle-backend-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgL0k5quGblFhRJxysoLM3chMm5RXiKD4',
    appId: '1:415414697651:ios:e19f6348298bad65cbbac6',
    messagingSenderId: '415414697651',
    projectId: 'ushuttle-backend-v2',
    storageBucket: 'ushuttle-backend-v2.appspot.com',
    iosClientId: '415414697651-01kmkui4unt6gag4b5eunuch2cinl7cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ushuttlev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgL0k5quGblFhRJxysoLM3chMm5RXiKD4',
    appId: '1:415414697651:ios:e19f6348298bad65cbbac6',
    messagingSenderId: '415414697651',
    projectId: 'ushuttle-backend-v2',
    storageBucket: 'ushuttle-backend-v2.appspot.com',
    iosClientId: '415414697651-01kmkui4unt6gag4b5eunuch2cinl7cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ushuttlev1',
  );
}
